=== Schveitzer/testes_api_zedelivery/base-files/schema_user_1.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "isActive": {
      "type": "boolean"
    },
    "picture": {
      "type": "string"
    },
    "age": {
      "type": "integer"
    },
    "gender": {
      "type": "string"
    },
    "company": {
      "type": "string"
    },
    "email": {
      "type": "string"
    },
    "phone": {
      "type": "string"
    },
    "address": {
      "type": "string"
    }
  },
  "required": [
    "id",
    "name",
    "isActive",
    "picture",
    "age",
    "gender",
    "company",
    "email",
    "phone",
    "address"
  ]
}

=== Schveitzer/testes_api_zedelivery/base-files/user_2.json
[
  {
    "id": 1,
    "name": "Ballard Steele",
    "isActive": false,
    "picture": "http://placehold.it/32x32",
    "age": 29,
    "gender": "male",
    "company": "SPACEWAX",
    "email": "ballardsteele@spacewax.com",
    "phone": "+1 (892) 549-3680",
    "address": "394 Homecrest Court, Idamay, Oklahoma, 5281"
  },
  {
    "id": 2,
    "name": "Taylor Vazquez",
    "isActive": false,
    "picture": "http://placehold.it/32x32",
    "age": 35,
    "gender": "female",
    "company": "SILODYNE",
    "email": "taylorvazquez@silodyne.com",
    "phone": "+1 (956) 558-3367",
    "address": "907 Walker Court, Springdale, Marshall Islands, 5449"
  }
]
